export const allCards = [
  {
    id: 1,
    type: "Siparişler",
    title: "Siparişin kargoya verildi!",
    text: "1 iş günü içerisinde siparişin kapında.",
    icon: "package",
    iconColor: "#ffd670",
  },
  {
    id: 2,
    type: "Siparişler",
    title: "Siparişin kargoya verildi!",
    text: "1 iş günü içerisinde siparişin kapında.",
    icon: "package",
    iconColor: "#ffd670",
  },
  {
    id: 3,
    type: "Kampanyalar",
    title: "%10 İndirim",
    text: "Tüm ürünlerde Şubat sonuna kadar %10 indirim.",
    icon: "tag",
    iconColor: "#fb6f92",
  },
  {
    id: 4,
    type: "Kampanyalar",
    title: "%10 İndirim",
    text: "Tüm ürünlerde Şubat sonuna kadar %10 indirim.",
    icon: "tag",
    iconColor: "#fb6f92",
  },
  {
    id: 5,
    type: "Yorumlar",
    title: "Yeni yorum eklendi",
    text: "Geri bildiriminiz için teşekkürler!",
    icon: "comment",
    iconColor: "#60d394",
  },
  {
    id: 6,
    type: "Yorumlar",
    title: "Yeni yorum eklendi",
    text: "Geri bildiriminiz için teşekkürler!",
    icon: "comment",
    iconColor: "#60d394",
  },
];
